# Generated by Django 4.2 on 2023-06-01 13:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryname', models.CharField(max_length=200)),
                ('catagorynamebn', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('slug', models.SlugField(default='', unique=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NewsCategory',
                'verbose_name_plural': 'NewsCategorys',
            },
        ),
        migrations.CreateModel(
            name='NewsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sironam_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('homepage_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('highlight_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('title_bn', models.CharField(blank=True, max_length=500, null=True)),
                ('detail_bn', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('detail_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('total_views', models.IntegerField(default=0)),
                ('top_news', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('videolink', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('slug', models.SlugField(default='', unique=True)),
                ('Written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory')),
            ],
            options={
                'verbose_name': 'News Table',
                'verbose_name_plural': 'All News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
