# Generated by Django 4.2 on 2023-06-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscategory_slug_alter_newsdb_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategory',
            old_name='catagoryname',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='newsdb',
            old_name='detail_bn',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='newsdb',
            old_name='title_bn',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='catagorynamebn',
        ),
        migrations.RemoveField(
            model_name='newsdb',
            name='detail_en',
        ),
        migrations.RemoveField(
            model_name='newsdb',
            name='title_en',
        ),
    ]
