# Generated by Django 4.2 on 2023-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_catagoryname_newscategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newsdb',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
